[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme = "README.md"

title = "Legged Obstacle RL"
author = "Grigorii Sizikov"
maintainer = "Grigorii Sizikov"
description = "Unitree Go1 rough-terrain RL (IsaacLab + skrl) with MuJoCo sim2sim and real-robot deployment."
repository = "https://github.com/kittnablude/legged-rl-isaaclab"
keywords = [
    "unitree",
    "go1",
    "isaaclab",
    "skrl",
    "legged-robotics",
    "sim2sim",
    "mujoco",
    "rl",
]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "legged_obstacle_rl"

[isaac_lab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
